name: CI
on:
  push:
    branches: [master]
  pull_request:

jobs:
  build-pkgs:
    runs-on: ubuntu-latest
    name: Build Packages
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            packages/*/dist
            packages/*/dist-cjs
          key: ${{ runner.os }}-build-pkgs-${{ github.sha }}
      - uses: actions/setup-node@v2-beta
        with:
          node-version: "14"
      - name: get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: yarn install
        run: yarn --frozen-lockfile --ignore-scripts --silent
      - run: ./scripts/build-pkgs

  lint:
    runs-on: ubuntu-latest
    name: Lint
    needs: build-pkgs
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            packages/*/dist
            packages/*/dist-cjs
          key: ${{ runner.os }}-build-pkgs-${{ github.sha }}
      - uses: actions/setup-node@v2-beta
        with:
          node-version: "14"
      - name: get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: yarn install
        run: yarn --frozen-lockfile --ignore-scripts --silent
      - run: ./scripts/lint

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["10", "12", "14"]
    name: Test on Node ${{ matrix.node }}
    needs: build-pkgs
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            packages/*/dist
            packages/*/dist-cjs
          key: ${{ runner.os }}-build-pkgs-${{ github.sha }}
      - uses: actions/setup-node@v2-beta
        with:
          node-version: ${{ matrix.node }}
      - name: get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: yarn install
        run: yarn --frozen-lockfile --ignore-scripts --silent
      - run: ./scripts/test

  code-style-check:
    runs-on: ubuntu-latest
    name: Code Style Check
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: "14"
      - name: get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: yarn install
        run: yarn --frozen-lockfile --ignore-scripts --silent
      - name: prettier check
        run: ./node_modules/.bin/prettier --check .
